#!/bin/bash
echo " ..................................... "
echo "|                                     |"
echo "|              CSB Tools              |"
echo "|                                     |"
echo "| [1] or [u] - Restore U-boot         |"
echo "| [2] or -                                    |"
echo "|                                     |"
echo "|                                     |"
echo "|                                     |"
echo "|                                     |"
echo "|                                     |"
echo "|                                     |"
echo " ..................................... "
